/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hsae_d531mc_jni_JniManager */

#ifndef _Included_com_hsae_d531mc_jni_JniManager
#define _Included_com_hsae_d531mc_jni_JniManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hsae_d531mc_jni_JniManager
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hsae_d531mc_jni_JniManager_sum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_hsae_d531mc_jni_JniManager
 * Method:    clone
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hsae_d531mc_jni_JniManager_clone
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_hsae_d531mc_jni_JniManager
 * Method:    mult
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_hsae_d531mc_jni_JniManager_mult
        (JNIEnv *, jclass, jfloat, jfloat);
#ifdef __cplusplus
}
#endif
#endif
